### ISSUE TITLE
Option to hide original damage buttons

### ISSUE THREAD

**Issue by TomChristoffer** [reonZ/pf2e-toolbelt#10]
In the token target helper, I would appreciate it if you had the option to hide and/or remove the generic damage buttons and only use the target specific ones, as you could with Pf2e Target Damage. Additionally, a setting to make the buttons bigger more in the style of the generic damage buttons would also be appreciated.
![image](https://github.com/reonZ/pf2e-toolbelt/assets/68109732/7060032c-7c72-4d65-8d73-585379270562)

**Comment by reonZ** [comment]
that and a lot more have been added to the `1.20.0`
