### ISSUE TITLE
Target/Templet Helper not working

### ISSUE THREAD

**Issue by B03hmi** [reonZ/pf2e-toolbelt#104]
" have activated the Target Helper and the Template Helper. Now, when I cast a Fireball, for example, I get the normal 20-foot template button. When I click on it, the window doesn't open as shown with the Template Helper, where it should give an option to select what it should target.
![Unbenannt](https://github.com/user-attachments/assets/1b6a7c18-89a7-4c66-a12b-7554a2cec3c9)
![Unbenannt2](https://github.com/user-attachments/assets/12c17ccc-2610-4130-a8e2-042ab6ada2ff)
![Unbenannt3](https://github.com/user-attachments/assets/9425b3ee-9f56-4009-b7c3-953e048e4c65)

**Comment by reonZ** [comment]
Your scene has no grid.
