### ISSUE TITLE
[Feature]  Setting to Create Chat Message on Save

### ISSUE THREAD

**Issue by ChasarooniZ** [reonZ/pf2e-toolbelt#107]
continuation of #31 
Hi, I realized I didn't make the case for this setting very well, so I figured I'd reopen it and restate my request (if it's still a no go, that's fine)

So ideally i'd like:
- A toggle in the settings to create chat messages when you roll the save

I do understand that being able to have the original message (IE the target damage one) and the save message linked up isn't possible.

I just think it'd be nice so that any chat cards related to the saves might be shown (makes it easier for players to read the Modifiers Matter etc.)

But in addition, it would allow me to continue and display effects based on the `createChatMessage` hook, as opposed to having to hook off of say a die roll etc.

Anyway thank you for your module and consideration

**Comment by reonZ** [comment]
not ony would this create redundant data but it will displace the original message (out of screen after a few targets) which means people will have to scroll back not only to make their saves but also to apply the damages which is like half of the reason this feature exists
