### ISSUE TITLE
Saves in template helper and target helper not working

### ISSUE THREAD

**Issue by StigerPL** [reonZ/pf2e-toolbelt#112]
When using template helper or target helper, when rolling saves with the save button, the roll is called but not saved. Example video:

https://github.com/user-attachments/assets/07583736-cef6-467d-993f-960e7c7c361e

Pasting error message below:

Uncaught (in promise) TypeError: undefined. window.pf2eMm?.getSignificantModifiersOfMessage is not a function
[Detected 2 packages: pf2e-toolbelt(2.25.1), system:pf2e(6.8.1)]
    at callback (targetHelper.ts:1314:48)
    at async CheckPF2e.roll (pf2e.mjs:1378:48387)
    at async StatisticCheck.roll (pf2e.mjs:1377:50839)
    
If you need anything else, like my module list or something, im happy to provide it. Thank you very much and sorry for the trouble!

**Comment by reonZ** [comment]
You need to update your modules. All of them.
