### ISSUE TITLE
[Feature Request] Shared Data on Vehicles

### ISSUE THREAD

**Issue by Axel-of-the-Key** [reonZ/pf2e-toolbelt#113]
I would like a way to link multiple vehicle tokens together, specifically to have them use the Shared Data feature to share HP. But as they are not actors, they do not have a Configure Menu that I can see. I would like if there was some way this option could be added for vehicles as well.

**Comment by reonZ** [comment]
Vehicles are actors but aren't creatures and lack the data NPC and characters have, there won't be any such option added to the module sorry.
