### ISSUE TITLE
[Feature Request] Add an option to switch Automatic Rune Progression bonuses from item bonus to potency bonus

### ISSUE THREAD

**Issue by SoupcanAnthill** [reonZ/pf2e-toolbelt#15]
When using the default ABP rules, it sets what would be a +1 item bonus to strikes to a +1 potency bonus, letting it stack with item bonuses from other sources, such as War Blood Mutagen. It would be great to be able to switch ARP to give potency bonuses as well, replicating what used to be possible with ABP and PF2e Workbench's "Enable item bonuses with ABP" option.

**Comment by reonZ** [comment]
This is an unreasonable request, there is no reason to implement a way to let you stack unstackable bonuses, pf2e is balanced around that.

The workbench setting was there to re-enable item bonuses that were disabled by ABP, it was so you could take advantage of equipment that would increase skill/perception/save checks (which were replaced by their own potency bonuses with ABP), not so you could "cheat" and further increase your attack rolls (this was just a byproduct of it that you could take advantage of).

ARP doesn't disable anything, all it does is automatically add the runes on the items the same way you would do it manually, so every item bonus works, there is nothing to be changed.
