### ISSUE TITLE
Cant install the module

### ISSUE THREAD

**Issue by Javierusan** [reonZ/pf2e-toolbelt#17]
Hi, when i try install the module, an error said: "Cannot be enabled due to issues in required dependencies", can you help me? Thx.

**Comment by reonZ** [comment]
this message shouldn't show up during installation, but when you try to activate the module in your world.

anyways, you need to have `libwrapper` installed as well, it should have asked you to install it at the same time you installed `PF2e Toolbelt`

**Comment by Javierusan** [comment]
Thank you. It works now. Although I don't know how to use the Target Token Helper to apply damage to target. Can you help me, pls? I have activated the module, but I can't find where to activate this function.
Thx.
