### ISSUE TITLE
Localization compatibility for Target Damage open sheet button

### ISSUE THREAD

**Issue by Cuingamehtar** [reonZ/pf2e-toolbelt#19]
Could you please use a custom language key for Open Sheet button in the Target Damage menu?
It currently uses `PF2E.Actor.Party.Sidebar.OpenSheet`. And while in English it just says "Open sheet", in Russian we explicitly localized it as "Open Party Sheet" because it's in the Party subcategory.
And unfortunately there is no generic Open Sheet string in the system to be used.

**Comment by reonZ** [comment]
i will do that

**Comment by Cuingamehtar** [comment]
Thank you.
