### ISSUE TITLE
[Feature Request] Target Token Helper - Chat, improvements for mass rolls

### ISSUE THREAD

**Issue by manolodantonio** [reonZ/pf2e-toolbelt#22]
Thanks for this great mod!

When targeting lots of creatures, with the current interface there is a lot of clicking for rolling saves and assigning damage.

Use case: 
Template has been placed and 10 tokens targeted. Now i click the Roll Damage chat button.
For each one of the 10 creatures, i have to press the "roll saving throw" button, and then the suggested damage button.

I would love to see the following:

1) - Option to auto roll the saving throws for all the targeted creatures. 
The creator of the template already decided the targets with the target pop-up, 99% there is no doubt they have to save. The roll save buttons are also very small, and misclicking is not unusual.

2) - Button to assign all suggested damage
If targets are correct, i usually click all the assign damage buttons. This operation is a bit painful, also because the confirmation messages makes the buttons scroll up. I would like to just click 1 big button and assign them all. 
Even better, this button should activate the suggestions only in the rows where the choice has not been made - in case i would like to manually assign damage to just 1 or 2 creatures, and follow the suggestion for all the rest.

I understand PF2 system has an idea about keeping things like in "real" table gameplay, but i see this as an automation module\qol that could benefit from this changes.

**Comment by reonZ** [comment]
There are two components to your request:

1. As you pointed out, the system devs don't like full automation and as someone who work closely to the system, i try to follow their vision as much as possible even though i stray from it on occasion
2. I need to find a way to incorporate it seamlessly into the current design and have not yet found something that i liked

It may eventually change at some point in the future, but no promises.
