### ISSUE TITLE
Target Token in Chat is not working as expected.

### ISSUE THREAD

**Issue by gkanks** [reonZ/pf2e-toolbelt#27]
The target token is identified but the buttons to target it do not appear when set to big or small. 

![image](https://github.com/reonZ/pf2e-toolbelt/assets/93349362/845e9893-996e-4a82-98f1-ba8779789293)

**Comment by reonZ** [comment]
i would probably test without any module then, nobody have reported such issue and i didn't experience it myself

**Comment by gkanks** [comment]
Yeah, it turns out that the dScryb module is the trouble. It is hiding the buttons in the chatlog. Once it is disabled the buttons appear for even old messages in the chatlog. Tried setting its priority to the lowest in libWrapper, even though toolbox does not seem to utilize libwrapper and that was not helpful.

Since dScryb is a very useful service which I use regularly and it works fine with the older PF2e Target Damage module I will have to go back to using it instead of toolbox. No big.
