### ISSUE TITLE
Target token helper shows NPC rolls to PCs, despite everything else being hidden from them

### ISSUE THREAD

**Issue by EgresMC** [reonZ/pf2e-toolbelt#28]
In my last session a PC used a Fireball spell against an NPC. 

After rolling for damage, Target Token Helper allowed me (the GM) to roll the Reflex save, and apply half damage to the NPC.

The problem is that my PCs saw the NPC Reflex roll, despite the fact that I have everything set to hide NPC rolls.

In fact, aside from the aforementioned scenario, no other NPC roll was shown to the PCs during the session.

I replicated the scenario, and every time the NPC Reflex roll gets shown to the PCs.

**Comment by reonZ** [comment]
Players now see the result of rolls made by NPCs yes, but no information about the rolls is shown if you have the system metagame settings to hide them.

![image](https://github.com/reonZ/pf2e-toolbelt/assets/651462/dbe89659-abc5-4de5-838e-5eb2ddd070e3)
this is with everything hidden, as you can see, we dunno what the die result was, we don't see any modifier.

![image](https://github.com/reonZ/pf2e-toolbelt/assets/651462/3ea2c715-a6d9-4e4c-8b5c-cb838152824a)
And here is with nothing hidden.

**Comment by EgresMC** [comment]
thanks for the quick response.

There's something I'm definitely missing here: why do the PCs see the GM's roll while using Target Token Helper, while they don't see it with other NPC's rolls?

I'm talking about the physical representation of the die, with the Dice so nice module.

Maybe it's an interaction with this other module.

**Comment by reonZ** [comment]
People wanted support for dice so nice so it was added but i don't use the module myself and don't really know how it works, so the implementation is most likely half assed.

**Comment by reonZ** [comment]
The latest `1.41.1` will now roll ghosted dice

**Comment by EgresMC** [comment]
Thank you. It works flawlessly!
