### ISSUE TITLE
Hero Actions : Translation support

### ISSUE THREAD

**Issue by Araluen124** [reonZ/pf2e-toolbelt#29]
Hi, there is some kind of problem with the translation of hero actions, My players are getting an english text for the description of the action while i am getting a french description with an english name (My table plays in french) this is a problem for the less multilingual of us and i am wondering if the language could be a setting so my players can understand their hero actions (I can help for the translation if needed)

**Comment by reonZ** [comment]
the description of the hero actions are not made by this module, everything is in the pf2e system, look for `Hero Point Deck` in the compendium, the module only offers a way to manage and use them, but all the text is in the system.
