### ISSUE TITLE
[Feature Request] Add "saving-throw" type to chat card

### ISSUE THREAD

**Issue by ottyn** [reonZ/pf2e-toolbelt#33]
When using the Target Helper options in Toolbelt, on the chat card for saving throws (either spell or damage), Roll Inspector does not show the "saving-throw" type on the card after adding targets.

![no-type](https://github.com/reonZ/pf2e-toolbelt/assets/97130150/dd5ab7c1-4349-4f8f-a806-573c4a9e9565)

While if you select the target itself and click the Save DC button to roll the save the resulting chat card has the "saving-throw" type.

![typed](https://github.com/reonZ/pf2e-toolbelt/assets/97130150/7393f3ec-d79a-4123-9a98-6a8675aa8aef)

Can this type be added to the Target Helper chat card rewrites for saves if possible?  The check for the "saving-throw" type is used by some automation scripts that I use.

**Comment by reonZ** [comment]
I am pretty sure it is a bad idea to mess with selectors and roll options, it could mess up the system rule elements.

Even though the module handles saves on the damage message, it is a damage message nonetheless, i don't feel comfortable changing that.

You should try to update your scripts instead to incorporate damage messages that have saves added to them.
