### ISSUE TITLE
Targetting assistance

### ISSUE THREAD

**Issue by Mermut** [reonZ/pf2e-toolbelt#34]
The PF2e Target Damage module says it's obsolete and that toolbelt has the functionality.
I haven't seen a way to duplicate the functionality with toolbelt. (ie if the PCs target a foe, it's got a listing to damage the foe in the chat window so I, as GM, don't have to manually select each foe in turn to do damage manually).

I'm guessing there is something I'm missing...

Figured it out.... but if the players don't set things up as well... it doesn't work at all for the GM either, which is problematic, since the primary purpose of the replaced mod was to make things easier for the GM.

That's going to be a.. uhm... challenge.. for some of my players
Oh well.. I know what I'm doing at the beginning of all my up coming sessions

**Comment by reonZ** [comment]
> but if the players don't set things up as well... it doesn't work at all for the GM either

if this is true then it is a bug, but have you actually experienced that or are you just making an assumption about it?

**Comment by reonZ** [comment]
I just created a new world, enabled the world setting and the client setting on the GM account, then logged with a user that didn't have the client setting enabled and it works fine on the GM side.

**Comment by Mermut** [comment]
I'll check again. I ran into pf2e target damage being disable last night during a session, so things were rather chaotic.
