### ISSUE TITLE
Can players see/use Target Token Helper?

### ISSUE THREAD

**Issue by ksignorini** [reonZ/pf2e-toolbelt#35]
Is Target Token Helper strictly a GM tool? Can players see the buttons and help the GM by applying damage to the targets?

If not, is there any way to hide the name of the target on the card for players? (Since the name of target appears at the bottom of the damage card, but the buttons do not.)

Image of player view of card:

<img width="283" alt="image" src="https://github.com/reonZ/pf2e-toolbelt/assets/6867660/cb5a14c8-08b5-472d-9b64-0f20405cb25a">

**Comment by reonZ** [comment]
No, foundry doesn't allow user to update an actor they do not own and this module will not circumvent that.

Players can never apply damage to NPCs so there is no reason to show the buttons, clicking the `+` button will show them though, they are not completely gone.
