### ISSUE TITLE
Template Targeting not working

### ISSUE THREAD

**Issue by kainpen** [reonZ/pf2e-toolbelt#37]
I am  testing the Module, for my game, and I am logged in on the forge as GM and trying to use the target Template targeting, but it is not doing anything.
The box pops up but nothing actually targets in the log or on the screen. in combat screenshot of spell being cast.
![image](https://github.com/reonZ/pf2e-toolbelt/assets/85844266/1b66d4bd-1001-4333-97ae-69f335fc9d54)

Screenshot of placing the 20ft burst
![image](https://github.com/reonZ/pf2e-toolbelt/assets/85844266/f1074a8d-c46b-4bb8-8dfd-6b4bb4068bff)

Screenshot of box popping up like it is supposed to 
![image](https://github.com/reonZ/pf2e-toolbelt/assets/85844266/5b641ef9-6d18-483f-a6a6-e5ffa99800a8)

I accept the defaults and their is no change in chat log or on screen to indicate targets
![image](https://github.com/reonZ/pf2e-toolbelt/assets/85844266/b35fcac0-d8d4-43b4-8e8b-2a63e438c774)

I roll the damage next no change expect to set targets for message.
![image](https://github.com/reonZ/pf2e-toolbelt/assets/85844266/0b304d3a-d1d5-4531-a67a-610cb65e4ada)

I click that and nothing happens.

If I manually select targets and selects set targets for message that portions works. as seen here.
![image](https://github.com/reonZ/pf2e-toolbelt/assets/85844266/7c2f78f4-bde4-4d21-b2cb-eb203753006a)

Same thing is happening on playerside. this is version of Foundry and Game set.
![image](https://github.com/reonZ/pf2e-toolbelt/assets/85844266/a89c9ad3-cf06-425e-859e-3210cdf393ce)

**Comment by reonZ** [comment]
You are on a gridless scene
