### ISSUE TITLE
Target Token Helper

### ISSUE THREAD

**Issue by xanstin** [reonZ/pf2e-toolbelt#39]
Is there something else that needs to be enabled elsewhere to get the popup to roll all saves vs click them individually? I am not getting that option.

![image](https://github.com/reonZ/pf2e-toolbelt/assets/26841771/996e65e2-529b-4be7-9d63-cd74ec550070)

**Comment by reonZ** [comment]
> A GM can right click on a message with saves and select the Roll All Saves option to roll the save for all the NPCs that have yet to roll.

**Comment by xanstin** [comment]
Yes I am the GM and I right click and that roll all saves option is not coming up I can only click the individual fortitude saves. That is the issue

**Comment by xanstin** [comment]
![image](https://github.com/reonZ/pf2e-toolbelt/assets/26841771/e31b9706-bb3a-48b1-98d9-c71ec9a15e44)
I dont get this context menu. I get the one posted above.
