### ISSUE TITLE
Target Token Helper Context Menu Issue still Persists.

### ISSUE THREAD

**Issue by xanstin** [reonZ/pf2e-toolbelt#40]
Ticket was closed without problem being understood with a generic answer from Wiki.

https://github.com/reonZ/pf2e-toolbelt/issues/39

I am the GM. I have a roll that has Saves shown by the fortitude symbol with the dice.  I right click the chat and my context popup menu doesn't have all the options indicated on the instructions page/video. 

This is what I get
![image](https://github.com/reonZ/pf2e-toolbelt/assets/26841771/530acd6e-b71e-4aac-8273-925dedfdf49b)
After clicking one persons save.
![image](https://github.com/reonZ/pf2e-toolbelt/assets/26841771/abaf02cf-2f0f-4799-9c73-0de24f31053e)

This is what your help video suggests I should get.
![image](https://github.com/reonZ/pf2e-toolbelt/assets/26841771/5ffb29c9-96be-4f95-b574-6eab965e02f0)

**Comment by reonZ** [comment]
> A GM can right click on a message with saves and select the Roll All Saves option to roll the save for all the NPCs that have yet to roll.

NPC as in Non Player Characters, in your screenshots, those are player owned character
