### ISSUE TITLE
Target Token Helper Suggested Damage Help

### ISSUE THREAD

**Issue by xanstin** [reonZ/pf2e-toolbelt#41]
Strictly targeting NPCs I got the roll all saves to pop up as designed. New issue I am having is the damage application suggestion based on save is not showing up for me. Saves went through when targeting NPCs should be 1 Success for Half Damage and 2 Failures for Full Damage but no buttons are highlighted. 

![image](https://github.com/reonZ/pf2e-toolbelt/assets/26841771/96fa8668-b879-4246-ae3d-a8046332a31d)

Expecting to see this

![image](https://github.com/reonZ/pf2e-toolbelt/assets/26841771/7feb1fc6-2c3f-4f06-8ccb-050e95f81e5d)

I have the following metagame selected in settings

![image](https://github.com/reonZ/pf2e-toolbelt/assets/26841771/1dc8d669-4a53-4884-a33f-7333471b061a)

**Comment by reonZ** [comment]
this is not a basic save, so there is no way to interpret it as a damage modifying save
