### ISSUE TITLE
[Feature Request] Reinforcing Runes for shields with automatic bonus progression

### ISSUE THREAD

**Issue by Malkyn99** [reonZ/pf2e-toolbelt#42]
Title. Would be fantastic if this could be added, love the rest of the work you've done with it.

**Comment by reonZ** [comment]
Those are not part of the progression of fundamental runes, so i would say "no".

But i plan on redoing toolbelt completely in a not-to-far-but-not-to-close future, so i may be adding it as a option, who knows, i don't plan on doing anything for now though.

**Comment by reonZ** [comment]
I looked at the progression of the ABP in the GCB and saw no change, but it is a coin toss really.
Like i said, i don't plan on adding anything to toolbelt right now as i plan on remaking it, i am slowly working my way through my modules. But this will most likely make an appearance in the 2.0, even if behind a setting.
