### ISSUE TITLE
Target Token Helper not showing damage buttons on private rolls

### ISSUE THREAD

**Issue by simondw2000** [reonZ/pf2e-toolbelt#43]
I'm not sure if this counts as an issue or a feature request technically....
In the old PF2E Target Damage module, if the GM rolls privately, players would still get the damage buttons (Damage, Half, Double, Block) popup for them so they can apply damage. With Target Token Helper in Toolbelt, this does not appear to work.

GM Screenshot:
![image](https://github.com/reonZ/pf2e-toolbelt/assets/30345746/3ddc1749-0a89-4c05-8c3a-b2b2e9624ae3)

Player Screenshot:
![image](https://github.com/reonZ/pf2e-toolbelt/assets/30345746/ed12b91b-25df-450c-b2eb-7eedcad508b5)

The workaround here is to reveal the damage roll to players, but I would prefer to not need to do this if possible.

Foundry: 11.315
PF2e: 5.15.0
Toolbelt: 1.42.2

I have tested this with all modules disabled except for Toolbelt and dependencies.

**Comment by simondw2000** [comment]
@reonZ any chance this could be a feature request then?
I personally prefer to roll privately but like my players having the ability to apply the damage with a quick click.

**Comment by reonZ** [comment]
no can do, the module uses the original buttons in the message, if anything i will remove everything from the players perspective for private message.
