### ISSUE TITLE
[Feature Request] Hide saving throw results in Target Token Helper when GM rolls privately

### ISSUE THREAD

**Issue by simondw2000** [reonZ/pf2e-toolbelt#44]
I understand that showing the results of NPC saving throws in TTT was a design choice.

Would it be possible to have a setting to hide the results from players whenever the GM is rolling privately?

**Comment by WaterpoloBlock** [comment]
(Not a dev)
I have the same problem too. Although, I am comfortable with it showing the result (Critical Success, Success, Failure and Critical Failure). I’m just not a fan of the number value being shown.

But like the original creator said, it would be great if we had the option to limit this information.

**Comment by reonZ** [comment]
I will definitely look at removing the extra details from the players when the message is private.

**Comment by reonZ** [comment]
Extra rows won't appear on private message with version `2.0.0`

**Comment by simondw2000** [comment]
Hi @reonZ 
It looks like the update hasn't solved this request.

This is an example from the player view in my game taken just after updating Toolbelt this afternoon:
![image](https://github.com/reonZ/pf2e-toolbelt/assets/30345746/95361a57-8346-44da-8517-188b2f068890)

The saving throw was made by my GM account with rolling set to "Private GM Roll", and I also have "Show Check Outcomes" and "Show Roll Breakdowns" both disabled in the "Limit Metagame Information" settings.

**Comment by WaterpoloBlock** [comment]
Game Settings -> Pathfinder 2nd Edition -> Limit Meta Game Information
Show Check Outcomes Enabled
Show Roll Breakdowns Disabled.

### What the PC Sees:
![PC1](https://github.com/reonZ/pf2e-toolbelt/assets/73310678/5fcca3ca-9251-433d-b77f-543b26732d8f)


### What the Gm Sees:

![GM](https://github.com/reonZ/pf2e-toolbelt/assets/73310678/586f2c86-8924-4437-86a8-26c035763922)



Just to throw in my cents, **I’m happy with how the update is.**

Would it be nice if the player couldn’t see the total dice value of npc’s saving throws? Yeah. But to me, I just see that as a “Cherry on top.”

The main deal breaker was the fact the dice modifier was shown. **Which you fixed and I thank you for.**

@simondw2000 concern is also valid.

**Comment by reonZ** [comment]
@simondw2000 

Ok so i guess i didn't understand the original request, i thought you were talking about private message as in that kind

![image](https://github.com/reonZ/pf2e-toolbelt/assets/651462/5dbaaf92-2161-43f0-990d-0ac8c68b93e2)

I am not sure if i can accommodate your request, i will look into it though

**Comment by reonZ** [comment]
@WaterpoloBlock 

The system shows the total result using your settings, so there is no reason for the module to not.

![image](https://github.com/reonZ/pf2e-toolbelt/assets/651462/d3444001-e808-472c-b867-90f61aa6778c)

**Comment by simondw2000** [comment]
> @simondw2000
> 
> Ok so i guess i didn't understand the original request, i thought you were talking about private rolling as in that kind
> 
> ![image](https://private-user-images.githubusercontent.com/651462/328260721-5dbaaf92-2161-43f0-990d-0ac8c68b93e2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUwMTY0NDUsIm5iZiI6MTcxNTAxNjE0NSwicGF0aCI6Ii82NTE0NjIvMzI4MjYwNzIxLTVkYmFhZjkyLTIxNjEtNDNmMC05OTBkLTBhYzhjNjhiOTNlMi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTA2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUwNlQxNzIyMjVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zY2ZhYTExZmYwYmIzMmJiMTgzYWFiN2Q0NjJiYmI5NWI2NjJjMDNlY2I2ZmM2ZDFiZDk2Y2Q1N2FlNzY5ZTJjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.ih4IM-Mqj-C3AxkppwiHRRQz3prOhopH1lDGqHAFY0U)
> 
> I am not sure if i can accommodate your request, i will look into it though

Thanks @reonZ. Fingers crossed you can do it.

**Comment by reonZ** [comment]
Next update will have a way for GMs to private roll their saves.

![Foundry_Virtual_Tabletop_zrfsvKaoo2](https://github.com/reonZ/pf2e-toolbelt/assets/651462/5c70c069-b3bf-4768-806a-063982fbe0fb)

**Comment by simondw2000** [comment]
Just updated and tested. It's working perfectly!!
Thanks @reonZ
