### ISSUE TITLE
[Feature Request] Use custom group names in Spell Summary

### ISSUE THREAD

**Issue by Axel-of-the-Key** [reonZ/pf2e-toolbelt#46]
We have limits as to what "spellcasting type" a new spellcasting entry is. While the Spell Summary feature excellently groups them together without making them all work the same, some spells (such as from items) can only be put under a certain category that ultimately will not make sense. This can be fixed in the normal view by naming that group something better (like "Wands" or after the specific equipment granting you that spell). However, in Spell Summary it will only show Innate/Prepared/Spontaneous/Focus and not utilize the custom name field. It would be great if the custom field name would be placed in the category column instead so we can more easily keep track of where our spells are coming from.
![image](https://github.com/reonZ/pf2e-toolbelt/assets/8282745/2459fe1a-e6d1-4cac-9c90-5ef6253ef285) In this picture you see that I have named this "innate" spells group after the item that grants those spells.
![image](https://github.com/reonZ/pf2e-toolbelt/assets/8282745/5abb6231-c11c-4b62-ac94-237a3f36ba35) However you can see here that it is only given the category of Innate still despite having a custom name.

**Comment by reonZ** [comment]
After looking, there is not enough space for it when using the regular sheet width.
Your screenshot is not representative of what a character sheet looks like.

![image](https://github.com/reonZ/pf2e-toolbelt/assets/651462/9e60b37b-1116-4689-a0d1-a37e2fabeec0)
here is how it looks like with just a basic naming structure.
