### ISSUE TITLE
Error when rolling a save with Target Helper using SubstituteRoll rule element

### ISSUE THREAD

**Issue by pedrogrullada** [reonZ/pf2e-toolbelt#47]
Sorry if you already saw this, I reported this on discord, but I didn't get a response, so I decided to report here as well so it's not lost. When rolling a save through target helper, if the roll is substituted with a SubstituteRoll rule element, it will give the following error and the result will not be shown.
![image](https://github.com/reonZ/pf2e-toolbelt/assets/103401186/5793e76b-3a33-467f-9234-9e50c24d276e)

**Comment by reonZ** [comment]
i will look into it when I am working on the feature

**Comment by reonZ** [comment]
The feature now accepts substitute rolls in the version `2.0.0`
