### ISSUE TITLE
[Feature Request] Display Notes in Target Token Helper

### ISSUE THREAD

**Issue by Ghostdesu** [reonZ/pf2e-toolbelt#48]
It is not uncommon to put relevant information about a creature/character's special saving throw interactions in a Note Rule Element.
Unfortunately, these are currently invisible when used with the Target Token Helper.

I suggest adding a button in these cases that would display the note on click (or maybe on hover).
It could look something like this: 
![Mockup of a damage roll including a saving throw note button in the shape of a font awesome info icon](https://github.com/reonZ/pf2e-toolbelt/assets/31375910/eb3b2c69-27eb-44c0-8e6a-f5f5a6332292)

**Comment by reonZ** [comment]
This has been added to the version `2.0.0` of the module
