### ISSUE TITLE
Hero Actions: Add Card

### ISSUE THREAD

**Issue by MrVauxs** [reonZ/pf2e-toolbelt#5]
Requesting the ability to add specific cards from the Hero Deck table. This setting could be limited to GM-Only, Player, and of course Disabled.

**Comment by reonZ** [comment]
do you mean specifically selecting a hero action manually ? i will look into it.

**Comment by MrVauxs** [comment]
Yep, manually selecting and adding a single card from the options in the table to a sheet.

**Comment by reonZ** [comment]
while this is something you could do right now using the API, i will work something out for the module

**Comment by reonZ** [comment]
you can now create a script macro containing
```js
game.modules.get('pf2e-toolbelt')?.api.heroActions.giveHeroActions(actor)
```
