### ISSUE TITLE
Target Helper - > Saving through result shows roll breakdown even if Disabled.

### ISSUE THREAD

**Issue by WaterpoloBlock** [reonZ/pf2e-toolbelt#52]
- Foundry VTT: 11
- Build: 315
- PF2e: 5.15.2

Active Modules:

- Libwrapper (1.12.13.0)
- Pathfinder Token Pack: Bestiaries (1.1.0)
- PF2e Toolbelt (2.0.2)
- The Forge (1.14.9)

Game Settings -> Pathfinder 2e -> Limit Metagame Information.
Show Roll Breakdowns and Show Check outcomes are the problem children.

So in my game, I typically have “Show check Outcomes” enabled. Apart from secret checks, I’m happy for my players to know if they (Crit) Failed or (Crit) Succeed. But I don’t want them to know the rolls nor breakdown for my npc’s. Hence why I keep “Show Roll Breakdowns” disabled.

Testing with a player account for target helper. If I set Show Roll Breakdowns to disabled and Show Check outcomes to enabled. It will show the result of there saving throw with a roll break down. I was expecting it to behave like the Pathfinder 2e game. With the given settings enabled/disabled when making a strike or action against a target: Instead of showing the dice value it spits out Crit Fail, Fail, Success or Crit Success to the Player.

![1_Disabled](https://github.com/reonZ/pf2e-toolbelt/assets/73310678/82987c6b-ffc3-4758-adb1-1b214e74e535)

To hide it, I also need to have “Show Check Outcomes” disabled. Now it won’t break down the roll, but it does show the dice result. 

![Both_Options_Disabled](https://github.com/reonZ/pf2e-toolbelt/assets/73310678/167932cc-82f1-45e6-bb9e-1d23413ce188)

If possible, it would be great if the module could adhere to the settings for “Show Roll Breakdown.” Like, if it were disabled it won't show the roll break down for saving throws made. Even if "Show check outcome" is enabled. Else the players are getting some free meta game information. Even better if instead of showing the saving throw total value it just tells the player if the npc (Crit) Failed or (Crit) Succeeded.

**Comment by reonZ** [comment]
As far as i could test, the module shows exactly the same info the system would. The screenshot following is from a player's perspective using the same settings as yours.

![image](https://github.com/reonZ/pf2e-toolbelt/assets/651462/20eb67a4-9283-4afa-b1a7-02666ecec9a2)

The only difference between the regular save roll and the inline one is that it tells you right away that the die was a `4`, but unless your players can't do `27 - 13`, this isn't an issue.

**Comment by reonZ** [comment]
As far as i could test, the module shows the same info the system would. The screenshot below was taken from a player's perspective using your settings.

![firefox_zdaORUxVnu](https://github.com/reonZ/pf2e-toolbelt/assets/651462/c17d6121-425f-4136-9219-b5ab21cc2ce1)

The only difference between the regular message and the inline one is that it tells you straight away that the die was a `4`, but unless your players can't do a subtraction, this isn't really an issue.

Unless i am missing something else.

**Comment by WaterpoloBlock** [comment]
I had thought with Roll Breakdown disabled, and Show Outcome enabled. It would have operated like how Vanilla Pathfinder 2e with actions against npc's. Where it informs the player of the outcome not the dice result, even if the mouse cursor is hovering over it. 

I did enable Work Bench for the Disarm Action to work. My mouse is hovering of The Failure for Athletics check, Snip it didn't grab my mouse.

Player Perspective:
![image](https://github.com/reonZ/pf2e-toolbelt/assets/73310678/abffda37-b584-4643-9c7f-31f1e61c9a13)



GM perspective:
![image](https://github.com/reonZ/pf2e-toolbelt/assets/73310678/cc33e539-b67b-4cf5-9f2f-5bab50c41c9c)

**Comment by reonZ** [comment]
those aren't save checks and i showed you in the screenshot what a regular save check looks like with your settings, so unless you can show me where i misunderstand, i can't help you.

**Comment by WaterpoloBlock** [comment]
The option Show Check outcomes. I like it, because it’ll tell the player if they (Critically) Failed or (Critically) Succeed an action against an npc. All without telling the AC/DC of the NPC. See above with the unarmed strike and Disarm action I did.

However, if I have Show Check outcomes enabled and Show Roll Breakdown disabled. Target helper will show the players the NPC’s dice value of the saving throw.

Like with your example, they rolled 14 on their reflex save, hovering over it, shows they rolled a 4. The Player could easily figure out the creatures Reflex save without ever having to do a Recall Knowledge check.

But for some reason, if I want to hide the roll break down on Target Helper I have to also disable  "Show Check Outcomes."

If it's still confusing you can close this ticket.

**Comment by reonZ** [comment]
> hovering over it, shows they rolled a 4

This is simple math: 27 - 13 - 10 = 4

The `4` is not a secret, anybody can figure it out because the other numbers are there, shown by the system. It shows the DC `27`, says that you missed by `13` and then that it is a critical failure so `-10`.

**Comment by reonZ** [comment]
I will make the change
