### ISSUE TITLE
[Feature Request] Bring back individual infinite inventory

### ISSUE THREAD

**Issue by Pyroman2xxx** [reonZ/pf2e-toolbelt#54]
I am not sure if you removed this feature due to limitations. I had been using this to have some items with limited quantities with the rest being unlimited. I can always just make a duplicate vendor with one being unlimited but the gold purse from selling items will then be split between them.

Is it possible to use the share data feature to pool the filter gold purse on merchants? I could not see any way to do it.

**Comment by reonZ** [comment]
i don't plan on bringing it back
