### ISSUE TITLE
2.5.0 update not working SETUP.PackageUpdateCoreundefined

### ISSUE THREAD

**Issue by jaredthaler** [reonZ/pf2e-toolbelt#56]
Pretty much what it says in the title.  I have 2.4.0, when I click update I get a Warning SETUP.PackageUpdateCoreundefined and the update does not install

**Comment by reonZ** [comment]
Sadly foundry makes cross versions difficult for users, it doesn't allow you to automatically update to a version other than the latest, and since the latest version is for the v12, you can't update on v11 automatically anymore.

You need to do it manually by using the manifest link directly, this is out of my control.

**Comment by johncarney** [comment]
> You need to do it manually by using the manifest link directly, this is out of my control.

Any chance you could pop this in the README with instructions? Or better still, build cross-version betas on a branch. The people that need to use them will not mind installing from branch manifests, whereas people running games and need things to Just Work™ won't be inconvenienced.

**Comment by reonZ** [comment]
If i knew things would turn like that, i would have taken another route, but i didn't think foundry wouldn't be able to do something as simple as only trying to update modules that are compatible with the currently installed version.

Now everything is merged into master and be listed, i don't feel like messing with everything trying go back. People gonna have to make do with the way things are until they decide to switch to v12.

**Comment by johncarney** [comment]
Yeah, I think that's something Foundry should work on; making version transitions easier to manage for module developers.
