### ISSUE TITLE
Merging attacks loses persistent damage

### ISSUE THREAD

**Issue by dagit** [reonZ/pf2e-toolbelt#59]
We noticed today when merging damage (flurry attacks) that the persistent damage was not applied when the damage was applied. This is on V11 of foundry. The persistent portion of the damage was listed as + 0 in the merged damage and then we needed to manually add the persistent damage effect to the target.

**Comment by reonZ** [comment]
I have found the issue(s) related to this, i am sorry to tell you that the fix isn't going to be available for the v11 version of foundry though.

**Comment by dagit** [comment]
Does that mean it will be fixed for v12?

**Comment by reonZ** [comment]
yes
