### ISSUE TITLE
Spells Summary No Longer Shows DC/Attack Modifier

### ISSUE THREAD

**Issue by WraithJT** [reonZ/pf2e-toolbelt#6]
As title says. This is more of an enhancement request than an actual "issue."
The Spells Summary is very nice and useful, but when you swap to it, you lose the information about your spellcasting DCs and attack modifiers. The previous, separate Spells Summary module had this information, in place of the range column (until it was updated prior to being merged into Toolbelt).

**Comment by reonZ** [comment]
it was actually removed almost [8 months ago](https://github.com/reonZ/pf2e-spells-summary/releases/tag/1.3.0) from the original standalone module, so this is not something new

you can get the spellcasting entry name and the DC value by hovering over the range of any spell, the consensus was that range is a more immediate needed information than the DC, so it was changed

![Foundry_Virtual_Tabletop_uz8ohltxJB](https://github.com/reonZ/pf2e-toolbelt/assets/651462/c6b5bfc3-d774-4fd1-866d-481b411b1bc5)
