### ISSUE TITLE
[Bug] Issue with adding effects

### ISSUE THREAD

**Issue by ChasarooniZ** [reonZ/pf2e-toolbelt#61]
This module seems to be breaking the ability to add on use effects to actions. Seems to always place the item you are trying to add the effect to

**Comment by reonZ** [comment]
You are right, weird that nobody ever raised the issue.
I will look into it but the fix is gonna have to wait for the v12 version.

**Comment by reonZ** [comment]
I have found and fixed the issue, if you can't wait for v12 and feel adventurous, you can make the change yourself directly in the file, this is a bit of a mess but nothing can really break even if you mess up, you can just uninstall/reinstall the module.

go in the module folder and look for the `main.js` file in the `scripts` folder, open it, look for this particular piece of code
```js
async function Np(e){let t=this.item;if(!this.isEditable||t.system.actionType.value==="passive")return;let r=await(async()=>{try{let n=e.dataTransfer?.getData("text/plain"),i=JSON.parse(n??"{}");return typeof i!="object"?null:i.type==="Item"?await Item.implementation.fromDropData(i)??null:i.type==="Macro"?await Macro.fromDropData(i)??null:null}catch{return null}})();if(!((0,c.isInstanceOf)(r,"ItemPF2e")&&r.isOfType("effect"))&&!(r instanceof Macro))throw(0,c.ErrorPF2e)("Invalid item drop");if(r instanceof Item){await t.update({"system.selfEffect":{uuid:t.uuid,name:t.name}});return}await sE(t,"macro",r.uuid)}a(Np,"actionSheetPF2eOnDrop");
```
and replace it with this 
```js
async function Np(e){if(!this.isEditable||this.item.system.actionType.value==="passive")return;let t=await(async()=>{try{let r=e.dataTransfer?.getData("text/plain"),n=JSON.parse(r??"");return typeof n!="object"?null:n.type==="Item"?await getDocumentClass("Item").fromDropData(n)??null:n.type==="Macro"?await getDocumentClass("Macro").fromDropData(n)??null:null}catch{return null}})();if(t instanceof Item&&t.isOfType("effect"))await this.item.update({"system.selfEffect":{uuid:t.uuid,name:t.name}});else if(t instanceof Macro)await sE(this.item,"macro",t.uuid);else throw(0,c.ErrorPF2e)("Invalid item drop")}a(Np,"actionSheetPF2eOnDrop");
```
like i said, even if this doesn't work, you can always re-install the module and forget about it

**Comment by ChasarooniZ** [comment]
Thanks, yeah I also always find it odd where like a module breaks functionality I'd consider to be pretty poor, and no one has commented on it. (I'm guessing people just don't generally make their own actions?)

**Comment by reonZ** [comment]
were you successful in applying the fix ?

**Comment by ChasarooniZ** [comment]
Haven't had a chance to, i'll try it
