### ISSUE TITLE
merge damage button in v12 seems to have no effect?

### ISSUE THREAD

**Issue by dagit** [reonZ/pf2e-toolbelt#63]
Testing out foundry v12 today. I tested the merge damage button. Clicking it doesn't appear to do anything. I opened up the js console and saw this exception every time I click the merge damage button
![image](https://github.com/reonZ/pf2e-toolbelt/assets/384637/d556840b-2b8c-4acb-9336-abf759b0578c)

**Comment by reonZ** [comment]
I know where the error is located and can fix it, but i am not 100% in which condition it appears, could you give me a step by step exact way to reproduce it pease ?

**Comment by reonZ** [comment]
Ok i found that it happens when using damage from a consumable source (wand, scrolls)

**Comment by dagit** [comment]
The character I was testing with is a monk with handwraps that have a fire rune. I only mention it because I don't know if your fix includes runes.

**Comment by dagit** [comment]
Okay, I tested it. Your fix works perfectly for my monk player. Thanks!

Here is what the combined damage output looks like. Even the persistent damage is there and the formatting looks good (that was an issue on v11).

![image](https://github.com/reonZ/pf2e-toolbelt/assets/384637/d228b319-77b2-473e-876e-a5a276e95bfa)

**Comment by reonZ** [comment]
something is weird with that name

**Comment by reonZ** [comment]
![image](https://github.com/reonZ/pf2e-toolbelt/assets/651462/7e486a67-b62d-4023-9f9e-67d54114c92a)

this is better
