### ISSUE TITLE
[Feature Request] all to dragon & drop conditions onto unowned tokens

### ISSUE THREAD

**Issue by manuel-hegner** [reonZ/pf2e-toolbelt#65]
> Giveth no longer allows to drag & drop effects/conditions onto unowned actors, the feature is strictly reserved for giving "equipment"

This feature was removed from the Giveth module. Is there any chance to revive it in some way or shape? It was really useful.

**Comment by reonZ** [comment]
No, it was not 100% viable, so i decided to not re-implement it on the v2.
