### ISSUE TITLE
[Feature Request] Ability to include scrolls in containers in spell summary

### ISSUE THREAD

**Issue by ConnorJBeck** [reonZ/pf2e-toolbelt#69]
Unclear whether this is a bug or intentional, so I'll frame this as a feature request.

When I have a lot of scrolls, and some of them are more non-combat focused, I like to put them in my backpack since the additional action cost is unlikely to be relevant for them. However, when I store scrolls or wands in my backpack, the Spell Summary feature of pf2e toolbelt does not notice them, and does not list them in my available spells to cast. Notably, spells from Staves are always shown, regardless of whether they are in your backpack or not.

Since this may be a feature some users prefer, I'd very much enjoy a toggle in the settings that allows you to indicate whether you want to hide or show spells granted by consumables that are currently in containers.

**Comment by reonZ** [comment]
Scrolls & wands are governed by the system, if the system don't show them, then the summary won't either.
