### ISSUE TITLE
Template Helper shouldn't prompt for targets if there are no targets in the area

### ISSUE THREAD

**Issue by shemetz** [reonZ/pf2e-toolbelt#72]
Example where it shouldn't appear:
![image](https://github.com/user-attachments/assets/b08b1751-3f3e-42bf-a181-5f3692ed8feb)

This is relevant because pretty often spells do something in an area to e.g. make it difficult terrain or create a wall in it, and then this prompt is unnecessary and wastes a bit of time.

(implementing this change requires moving the "which tokens are inside this?" check to happen before rather than after confirmation, but, this shouldn't impact performance)

By the way, I think the word "Cancel" is a bit misleading there -- my first times, I mistakenly thought that it meant "cancel the template", but it doesn't.  I suggest renaming it to something like "No targets".

**Comment by reonZ** [comment]
I have thought about (after actually implementing it successfully) and decided to not do it, this will bring other issues like giving away the fact that no undetected tokens were caught in it.

I will still be implementing a way to skip the feature by holding `Ctrl` when placing a template.
