### ISSUE TITLE
Target helper saving throws not functional in foundry release 331

### ISSUE THREAD

**Issue by Taurias** [reonZ/pf2e-toolbelt#75]
Since updating to foundry v12 release 331, the target helper feature to roll saving throws for multiple targets does not function properly.
It displays as it should, but when you click the roll for rolling a saving throw, nothing happens. It doesn't register the dice roll to tell you if it succeeded or failed.

How I know it's foundry release 331:
I ended up disabling every other module I have save for toolbelt and its dependency. Got the same result.
Had a friend who has toolbelt functional who was on version 330, they had no issues at all. They updated to 331 and it started doing the exact same thing mine is doing.

**Comment by reonZ** [comment]
I am not exactly sure to understand your problem, but i tested and everything works for me:
https://github.com/user-attachments/assets/90e9f613-0edf-46fc-915f-0ac263532298

So i am gonna need more details, errors in the console and what not.

**Comment by micatron** [comment]
I am having the same issue, also in version 331. Everything works as normal like in your clip, except the save results don't get reported in any way and the damage/half/double etc buttons don't light up. This is the error I'm getting.

![tberror](https://github.com/user-attachments/assets/7c02a3a3-8dd0-481b-84b3-8339ac017246)
