### ISSUE TITLE
[Feature Request] Add "Services" to Better Merchant Sheets

### ISSUE THREAD

**Issue by TangledLion** [reonZ/pf2e-toolbelt#76]
Essentially the idea is you can set certain items in the merchant sheet as "Services" that when bought send a message to chat saying "[Actor] just purchased [ItemName]" followed by a chat card that can be customized with some simple scripting in the GM notes field. This could be used for spellcasting services for example Make an item called "Cast: Cleanse Affliction" with the description "Bobby casts _Cleanse Affliction_ on a willing creature of the buyer's choice." and the item icon is like, a hand or something. Then for the chat card, the GM could specify to make it send with the name, icon, and text of cleanse affliction but with some inline rolls at the end to represent the NPC's ability to cast the spell. Or buying a rune transfer service could just say "Carwoman takes the items involved in the transfer for 4 days, along with an additional amount of gold to cover the material cost of the transfer."  without an Item icon or title

**Comment by reonZ** [comment]
You can't cast spells from a loot actor, so this would already kill the feature entirely.

**Comment by TangledLion** [comment]
I'm not thinking to cast the spell to be clear. When I gave the spellcasting example I was thinking more the GM manually adding a inline roll prompt that matches the NPCs spellcasting modifier.

**Comment by reonZ** [comment]
This has been added to version `2.13.0`
