### ISSUE TITLE
Players unable to use save roll UI

### ISSUE THREAD

**Issue by xKillerbees** [reonZ/pf2e-toolbelt#78]
When players roll electric arc for example on another player, the save dice button is there on the damage roll but when it's clicked on, the result does not update on the damage card and the damage button does not highlight update. Console shows no errors.

If the GM clicks on any of the save rolls, then it does work and does update the card. 

Also wish there was a way to roll the save by the module directly on the spell and before the damage roll since it influences when people want to hero point reroll after they see the damage amount when a GM targets a player. 

PF2E: 6.2.3
PF2E Toolbelt: 2.11.1
Foundry: v12 331

**Comment by reonZ** [comment]
an error screenshot would be helpful

**Comment by xKillerbees** [comment]
I have tried disabling PF2e Dorako UI but no success.

https://drive.google.com/file/d/1q4nw57fT8sWf-spjVntqVeCCTZ9rnSPS/view?usp=sharing

**Comment by reonZ** [comment]
i can't go to your link, just drag & drop your image in the github comment directly

**Comment by xKillerbees** [comment]
I can't upload, I took a video and it is too large for Github. Tried compressing it too. 

https://youtu.be/Cm9aiaC22IQ

**Comment by reonZ** [comment]
You don't have a game master online,  players can't modify documents they don't own in foundry, so for the feature to work, the process is done by "asking" the GM to do it for the player, if none are online, nothing can happen.

**Comment by xKillerbees** [comment]
Duh, thanks

**Comment by reonZ** [comment]
I will add a notification for the feature that require a GM in the next toolbelt update.
