### ISSUE TITLE
Token Target Damage not working

### ISSUE THREAD

**Issue by HugoSimoes55** [reonZ/pf2e-toolbelt#8]
I have all the Token Target options selected. However, when I target a token and use an attack, the extra row of damage buttons per targeted token does not appear. This happens for both NPCs and PCs attacking and being attacked.

The following error appears in the console:
![image](https://github.com/reonZ/pf2e-toolbelt/assets/109922698/2816ce77-1f53-45ad-b119-4013d3b362f2)

Additionally, when I use the chat button to place a spell area, the popup appears asking what to target, but the tokens don't get targeted. No error in the console.

**Comment by reonZ** [comment]
the first problem should be fix with the `1.19.0`

for the template, make sure you are using a regular grid on your scene
