### ISSUE TITLE
Legendary Save Proficiency - Half Damage on Failure

### ISSUE THREAD

**Issue by chazpls** [reonZ/pf2e-toolbelt#80]
Creatures with legendary proficiency in a save take half damage when they roll a failure against a damaging effect. Currently, target helper still highlights the "full damage" button for these characters. Ideally it could automate to highlight the half-damage if you have one of these features (formerly called Greater Evasion/Juggernaut/Resolve but some classes now have class-specific names for these features).

**Comment by chazpls** [comment]
Rather than going off of the feature names, it would probably be much simpler to just check save proficiency level. **Every** feature that grants legendary proficiency in a save also causes you to take half damage from damaging effects on a failure. (I just validated this on AoN). Running off of save proficiency would also future proof this against feature name changes and new classes.

The Monk feature would also require special handling, since the Monk gets to choose which save they take to Legendary with their feature "Third Path to Perfection".

However, just for reference, here are the current features:

Greater Juggernaut
Greater Dogged Will
Third Path to Perfection
Greater Natural Reflexes
Greater Rogue Reflexes
Assured Evasion
Greater Mysterious Resolve
Greater Performer's Heart
Fortress of Will
Greater Resolve

**Comment by reonZ** [comment]
> Every feature that grants legendary proficiency in a save also causes you to take half damage from damaging effects on a failure. 

How would i know that a legendary save comes from a feature though?

**Comment by reonZ** [comment]
This is more complicated than i thought, because those features say
> When you roll a failure on the chosen type of save against an effect that deals damage, you take half damage.
But also
> When you roll a critical failure on the chosen type of save, you get a failure instead.

The issue is that the system already turn a critical failure into a failure, so when i do the checking, i can't know if the failure i have in the data is a real failure or is a modified critical failure.

**Comment by chazpls** [comment]
To my understanding there's no way (within the rules) to get legendary proficiency in a save outside of the features (listed above) granted by your standard class progression -- that would violate the core design tenets of the system. I've just checked on AoN and there definitely aren't any items that increase proficiency to legendary in this way (or to any level beyond trained, as far as I can find).

Even within Foundry, there's no way to adjust your save proficiencies without having one of these features on your sheet, so being granted an upgrade like this by GM fiat seems like a pretty limited edge case. However, you **could** just go off of the feature list -- but it would have to be updated when new classes are added, whereas just basing it on proficiency level would future proof it.

I do think it would be a really beneficial feature to have in the module, in large part because in one of my games for almost 12 sessions we had a player who didn't realize their Assured Evasion did this and were taking full damage every time they failed a save. Since it's part of the standard class progression and has no automation in Foundry, I think it's easy for players to miss this particular feature.

**Comment by reonZ** [comment]
I have implemented it already, i am just waiting before releasing a new version.

**Comment by reonZ** [comment]
This has been added to version `2.13.0`
