### ISSUE TITLE
Template Helper: "Include Self" not working with measurement controls

### ISSUE THREAD

**Issue by Aziareel** [reonZ/pf2e-toolbelt#81]
It appears, that I cannot toggle the Include Self option when placing templates via measurement controls.
It works with templates from items/spells that originate from an actor. But it would be nice if it also worked with templates placed from other sources.

Foundry Version: 12.330
Pathfinder 2e Version: 6.3.1
PF2e Toolbelt Version: 2.12.0
libWrapper Version: 1.12.15.0

Tested on a grid scene with no other modules activated other than the ones mentioned.

**Comment by Aziareel** [comment]
Maybe using the last selected token as "self" if the permissions allow it. For players it could default to the player character. But sounds too clunky.

Alternatively, a way to quickly place a template with an origin would help, too. I guess that was the actual intention of my initital issue.

**Comment by reonZ** [comment]
I don't think any alternative solution would be faster than just untargeting the token you consider as "self" before continuing whatever you are doing.
