### ISSUE TITLE
Feature Request - Allow Services to be affected by sell filter price ratios

### ISSUE THREAD

**Issue by JarobRo** [reonZ/pf2e-toolbelt#82]
It would be nice to be able to allow the new services feature to handle sell ratios, like consumables or other equipment.
That'd let us have discounted spellcasting (the services are nice, thank you!) and the like.

**Comment by JarobRo** [comment]
It still beats selling spellcasting as a consumable, and it could maybe be a toggle, so those who don't want the option don't need to take it.

**Comment by reonZ** [comment]
Services aren't foundry document with an already established price that you may feel the need to change based on a the merchant discount. Services are created on a per-merchant basis, they have no price but the one you set when you create them, so why not directly set the discounted price to begin with ?

**Comment by JarobRo** [comment]
It was just a thought due to the AP I'm running using Reputation, meaning the discounts on various merchants can change, including for spellcasting services.  Instead of having all the spells, I can just give spell ranks as services and manually adjust the price on just a couple to indicate the discount, rather than load up all the spells.  Either way, having the services available was a great add!

**Comment by reonZ** [comment]
I am gonna add a services ratio field on the left side of the merchant.
