### ISSUE TITLE
Raise a Shield macro is broken for GM

### ISSUE THREAD

**Issue by Phatepiclewt** [reonZ/pf2e-toolbelt#83]
Whenever I use the "Raise a Shield" action or corresponding macro as a GM with a unit selected, the "Raise Shield" effect will appear on the selected token and then immediately disappear. The "Raise Shield" effect will apply properly if I deselect the token before using the macro from the character sheet, or if I manually apply the effect from the compendium. I have isolated the problem to the pf2e-toolbelt module, although I can't find a particular setting that fixes it.

Edit: figured it out. The setting that was causing the issue is "Auto Self-Applied" under the Use Button category.

**Comment by reonZ** [comment]
You probably should push your investigation further and use toolbelt without any other module.

- the "Raise a Shield" macro doesn't interact with `Auto Self-Applied` at all
- the "Raise a Shield" action doesn't have any automation by default (which is what `Auto Self-Applied` here)
