### ISSUE TITLE
Not an issue but an idea

### ISSUE THREAD

**Issue by Dragonzofdeath** [reonZ/pf2e-toolbelt#89]
Sorry no where to place an idea... the use bottom would be awesome if you can have an option to use on non identity objects( just cause you don't know the food doesn't mean you can't eat it)

Also effects don't apply automatically, would be nice if they can pop up want effect to apply or make a same.

**Comment by reonZ** [comment]
I am kinda following the system on that one, there is no interaction with unidentified items usually in it.

I don't know what you mean by "Also effects don't apply automatically", if you enable the `Auto Self-Applied` setting then they will be.
