### ISSUE TITLE
[Feature] Expand the ability to add saves to any message

### ISSUE THREAD

**Issue by ChasarooniZ** [reonZ/pf2e-toolbelt#90]
The idea being i have aa save spell that doesn't have damage, currently the workflow to add all the targets to the save pop up is a pain, so if you could just drag the save to the feature/spell message it would be a nice way to handle this use case. (If it seems bad to happen in general maybe as amodule setting?)

**Comment by reonZ** [comment]
Your request isn't clear. Also why does

> currently the workflow to add all the targets to the save pop up is a pain

What popup?

**Comment by ChasarooniZ** [comment]
Hi sorry,

So the ideal workflow for new feature request is:
- Character sends chat card for Ability with save without Damage rolls
- You drag this save to the chat card
- It creates the the save card feature that it does on damage rolla

**Comment by reonZ** [comment]
The issue is, chat message that can have saves are the ones that can have targets, a damage message and a spell message without damage are easily identifiable (and already have some UI elements).

Other random messages aren't identifiable like that.

**Comment by ChasarooniZ** [comment]
Hmm in that case, honestly just a way to more easily generate the save list for things like creature abilities or the the Kineticist abilities (perhaps just something like `Alt + Clicking` the save)

But my end goal I guess is making saves for those things that don't have damage and aren't spells a bit easier than the current method of creating a fake damage roll, then adding the saves to that

**Comment by reonZ** [comment]
saves were never an isolated feature, they were an addition to damage, they were added to spells without damage because spells were already part of the workflow and as i said, easily identifiable.

loosely adding those features to any type of message isn't really something that can be done, there is no way to identify them and know where/how to modify them because there is no way to know their structure.

**Comment by ChasarooniZ** [comment]
👍

**Comment by reonZ** [comment]
I decided to tackle this, it will not work for any message, but i am adding support for "actions" messages at elast.

**Comment by reonZ** [comment]
I have added support for action messages and prompted save check messages in version `2.17.0`
