### ISSUE TITLE
Giveth - giving a spell effect doesn't work on Foundry V12.330, PF2E V6.4.1

### ISSUE THREAD

**Issue by CaptainCapibara** [reonZ/pf2e-toolbelt#91]
Giveth doesn't seem to be working on PF2E version 6.4.1. I am running Foundry V12 build 330.

Giveth is enabled and the module PF2E Toolbelt is enabled. PF2E is up to date at V2.16.0.

When one of my players tries to give a spell effect to another player, like a Spell Effect: Guidance for example, they get an error saying the user lacks the permission to create an item in parent actor.

I have checked the permissions, they have all permissions (as trusted players) to create new items. They can not delete tokens, create a playlist or modify configuration settings, all other permissions are activated. 

This worked in V11 but stopped working when I updated to V12.
I have tried disabeling and re-enabeling the module, with reloading the server after each change, but to no succes.

**Comment by CaptainCapibara** [comment]
One thing to add, Giveth does seem to work for giving items from one players inventory to another player. The item changes from players and I get a textbox in the chat.

**Comment by reonZ** [comment]
I am pretty sure you have been told already on discord that it was normal, so why create an issue here ?
