### ISSUE TITLE
[Feature Request] Hide saving throws rolled via chat card while using Dice So Nice!

### ISSUE THREAD

**Issue by joeparis** [reonZ/pf2e-toolbelt#93]
Request:

Please provide an option to show ghost dice and hide the result of saving throws rolled by the GM while enemy tokens have their name shown.

Details:

With tokens set to display their names to "Always For Everyone" and the Dice So Nice! (DSN) mod enabled, players see GM's dice rolls even when DSN is configured to show ghost dice for hidden rolls either "To All Players" or "To The Roll Author Only" and the GM's roll mode set to "Private GM Roll," "Blind GM Roll," or "Self Roll." I discussed this with DSN's author and he pointed out this code in Toolbelt:

![image](https://github.com/user-attachments/assets/83c0e180-a956-40e9-8377-0fb8cbb09ad7)

If this is a design choice, would it be possible to get an option to change this behavior and show ghost dice when they are rolled via the chat card?

https://github.com/user-attachments/assets/e8be97f7-30b4-41b5-a689-d3e538093994

The video above was recorded on a fresh install of Foundry V12.331 configured as follows:

1. Install Modules:
    * Pathfinder Second Edition system v6.4.1
    * Dice So Nice! v5.1.1
    * PF2e Toolbelt v2.16.0
2. GM Settings:
    * Core | Default Token Configuration | Display Name = "Always for Everyone"
    * Dice So Nice! | Show Ghost dice for hidden rolls = "To all players"
    * PF2e Toolbelt | Target Helper | Enabled
    * PF2e Toolbelt | Template Helper | Enabled
3. Player Settings:
    * PF2e Toolbelt | Target Helper | Enabled
    * PF2e Toolbelt | Template Helper | Enabled
4. Basic setup:
    * Add new user named Player2
    * Import Ezren (Level 5) Actor, add to The Party folder, give ownership to Player2
    * Import Goblin Commando Actor
    * Create new Scene, activate it, add Ezren and a Goblin Commando
    * In separate browser, log in as Player2

Example:

* Start an Encounter, add both Actors, roll initiative
* Ezren targets the Goblin, casts Fireball, and rolls damage
* GM makes Reflex Saving Throw via the Chat Card

Observed Behavior:

* Player sees the actual face value on the dice (Ghost dice setting is ignored)

Desired Behavior:

* Player sees the obfuscated value on the dice (Ghost dice setting is honored)

**Comment by reonZ** [comment]
I see, this is related to the private roll

**Comment by reonZ** [comment]
I meant that it was related to the feature to roll private saves that i added, this wasn't originally possible and therefore wouldn't have been a problem here, but now that it is possible to make a private save roll in the module, i see the issue.

The handling of private rolls was added very late as a [Feature Request] and when adding stuff later on, it is hard to have the big picture especially when trying to add support to a third party module that i don't even use.

**Comment by joeparis** [comment]
That was fast, thank you! I look forward to seeing it in the next release.

**Comment by reonZ** [comment]
This should be fixed in version `2.17.0`

**Comment by joeparis** [comment]
The fix works beautifully, thank you for implementing it and for how quickly you did it.
