### ISSUE TITLE
Feature Request: Add "Medium Buttons" to target helper

### ISSUE THREAD

**Issue by fraserstanton** [reonZ/pf2e-toolbelt#97]
I have a disabled player who can find it quite hard to click on those tiny "small" buttons. Any chance I can request a medium size or slightly bigger option? I do love the feature of the streamlined chat card, keep up the good work.
To clarify, I mean the tiny buttons to roll the save.
![image](https://github.com/user-attachments/assets/61e8887a-f8a2-468e-82af-7cb0c7481d60)

**Comment by reonZ** [comment]
I just increased slightly the size of the header icons and text. If this is still not enough, you can always make some changes using css on your own, this is not very hard and if you struggle with it, you can always come on the foundry discord to ask people to guide you.

**Comment by fraserstanton** [comment]
Awesome, thanks!
