### ISSUE TITLE
Giveth Not Working

### ISSUE THREAD

**Issue by Maelfros** [reonZ/pf2e-toolbelt#99]
Players unable to trade items with other player owned tokens. V12 Stable 7 Build 331.

**Comment by reonZ** [comment]
An error message would be useful, just saying "it doesn't work" isn't really. Also it works fine for me:

https://github.com/user-attachments/assets/58f83c62-04e7-4e30-b141-05733b669a95

Are you sure you have a GM online when trading ?

**Comment by Maelfros** [comment]
I am just an idiot and was using the mod wrong... thought there was a conflict! thanks for the quick response!
